// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOMJ7NOBOKxXk0kaEJqYZk5Fym2fvnjVs',
    appId: '1:930832494017:web:eab24fc3dade3b0c3a9340',
    messagingSenderId: '930832494017',
    projectId: 'youtube-clone-maaz',
    authDomain: 'clone-maaz.firebaseapp.com',
    storageBucket: 'youtube-clone-maaz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYB2tM4EbwwLh4NLY-8GQ_g0jLmH8_qlo',
    appId: '1:930832494017:android:8e290e8eb63113683a9340',
    messagingSenderId: '930832494017',
    projectId: 'youtube-clone-maaz',
    storageBucket: 'youtube-clone-maaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-LPAHuD1a_2FrYGhul6YhWJwbTMKrTU',
    appId: '1:930832494017:ios:32dddbd12e2f44113a9340',
    messagingSenderId: '930832494017',
    projectId: 'youtube-clone-maaz',
    storageBucket: 'youtube-clone-maaz.firebasestorage.app',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd-LPAHuD1a_2FrYGhul6YhWJwbTMKrTU',
    appId: '1:930832494017:ios:32dddbd12e2f44113a9340',
    messagingSenderId: '930832494017',
    projectId: 'youtube-clone-maaz',
    storageBucket: 'youtube-clone-maaz.firebasestorage.app',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOMJ7NOBOKxXk0kaEJqYZk5Fym2fvnjVs',
    appId: '1:930832494017:web:e5cef9c4c74e5ddb3a9340',
    messagingSenderId: '930832494017',
    projectId: 'youtube-clone-maaz',
    authDomain: 'clone-maaz.firebaseapp.com',
    storageBucket: 'youtube-clone-maaz.firebasestorage.app',
  );
}
